services:
  - type: web
    name: maso-awards
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server/server.js
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: maso-db
          property: connectionString

databases:
  - name: maso-db
    plan: free
    databaseName: maso_awards
    user: maso_admin

